### ISSUE TITLE
[REFACTOR] 멀티모듈 분리

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#122]
## 🔈 Issue

- 싱글 앱모듈에서 멀티 모듈로 다중화 작업을 하려고합니다.
- 한 번도 해보지 않아 돌다리도 두드리면서 공부하느라 조금 오래 걸립니다ㅠㅠ
- 현재 아직 멀티 모듈 정리가 끝나지 않아 끝난 이후에 약간의 연습 후 제대로 작업 시작하려고 합니다.

## 📑 To-do

- [x] 의존성 그래프 그리기
- [x] 릴리즈 전에 printStackTrace 지우기
- [x] Android Library Module 분리(feature, core, core-dependent)
- [x] 의존성 역전 해결
- [x] 안 쓰는 패키지 import 제거, import.* 라인 제거
- [x] 근데 data, core-common은 AndroidX 라이브러리 사용시 Android Library Module로 분리예정
- [x] 의존성 주입
- [ ] Navigation 해결
