### ISSUE TITLE
[FEAT] Multi Module 관련

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#125]
## 🔈 Issue

- 모듈 분리한 내용 회의 후 추가 요구사항 개편하려고 합니다.
- 네비게이션 모듈 삽입 혹은 모듈간 통신 처리 다음 이슈로 넣어두려고 합니다.

## 📑 To-do

- [x] 리소스 정리
- [x] 네비게이션 모듈 삽입
- [x] 각각의 navigate 처리
- [ ] core-dependent 리소스 추가
- [ ] 하나의 공통 리소스 모듈만 참조하게 변경

**Comment by KkamSonLee** [comment]
공유 리소스 안함!
