### ISSUE TITLE
[FEAT] 검색하기 Activity화 하기

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#132]
## 🔈 Issue

- 검색하기 로직 Fragment -> Activity로 바꾸려고 합니다.
- 하면서 로직 개선 할 예정입니다.
- HomeFragment도 그김에 기능 개선 하려고 합니다 ㅎㅎ

## 📑 To-do

- [x] SearchFragment to Change Activity 
- [x] LiveData to Change StateFlow
- [x] Logic Improvement
- [x] Repository Pattern Logic Improvement
- [ ] SearchBottomSheetFragment 로직 통일 시켜놓기
