### ISSUE TITLE
[FEAT] 알림 설정 UI & 기능 구현

### ISSUE THREAD

**Issue by jinsilWoo** [team-MUMENT/MUMENT-AOS#137]
## 🔈 Issue

알림 설정 UI 부분 다시 구현하고 기능 구현까지 하려고 합니다 :)

## 📑 To-do

- [x] 알림 설정 UI 
- [x] 알림 설정 기기 내에 접근 구현
- [x] 알림 설정 기능 구현
