### ISSUE TITLE
[FEAT] 홈, 검색 (SideEffect ViewState Event 통합 처리)

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#139]
## 🔈 Issue

- 평화형이 만들어놓은 SideEffect, Event에 따라서 처리 방식 통일 시켜놓으려고 합니다.

## 📑 To-do

- [ ] 홈, 검색 이벤트 Contract Object 생성
- [ ] 각각 이벤트 처리
- [ ] 각각 SideEffect 처리
- [ ] 정상 작동 확인
