### ISSUE TITLE
[REFACTOR] 레파지토리 패턴 적용

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#149]
## 🔈 Issue

- 오늘의 뮤멘트 관련만 지금 remote, local을 왔다리 갔다리 하는데 해당 로직이 레파지토리에서 합쳐져야 합니다!
- 하지만 지금은 따로따로 제공하고 있기 때문에 수정 해놓으려고 합니다!!
- 그김에 데이터 후 처리 해버리는 영역일부 data layer, domain layer 건드려서 바꿔 놓으려고 합니당

## 📑 To-do

- [x] today mument관련 로직 수정
- [x] data layer 전반적인 최적화
- [x] Repository 코드 수정 (Home)
- [x] UseCase 코드 수정 (Home)
- [x] 빨리 끝내기
