### ISSUE TITLE
[Chore] 파베 연결 및 알림 초기 설정

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#153]
## 🔈 Issue

- 파베 연결 정도만 해두려고 합니다
- 그김에 Sample 파일 정도는 넘겨놓겠습니다!!
- 그냥 푸쉬하려다가 혹시라도 conflict 날까봐 이슈 팠습니다.

## 📑 To-do

- [x] google-services.json 파일 추가
- [x] 의존성 추가(앱 수준, 프로젝트 수준)
- [x] 서비스 샘플 파일 만들기
