### ISSUE TITLE
[FEAT] 알림 관련 뷰 개발(소식 창, 좋아요 알림 알럿)

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#158]
### BaseActivity 추가
- BaseActivity의 애니메이션 추가해두려고합니다!!

### 소식창
<img width="171" alt="스크린샷 2023-01-09 오후 2 25 02" src="https://user-images.githubusercontent.com/15981307/211245511-83436546-626b-400b-96c3-790b2db9dfcf.png">

- 뷰 작업 먼저 해놓으려구 합니다~!!
- 해당 소식창은 홈에서만 접근 가능하니 home 모듈에서 작업 하도록 하겠습니다!
- 백그라운드에서 푸쉬 알림 클릭 시에 소식창으로 바로 갈수도 있으니 홈 Fragment를 BackStack에 두고 소식창이 뜨게 해놓겠습니당

### 알림 알럿
<img width="177" alt="스크린샷 2023-01-09 오후 2 25 10" src="https://user-images.githubusercontent.com/15981307/211245524-d26cbb8a-6411-434a-a1ca-00ce8484505e.png">

- 어디서든 나올 수 있는 화면이니 일단은 공용 모듈로 빼두려곤 하는데,, 공용 모듈이 너무 커지는 것은 곤란하긴 합니다...
- 고냥 해도 되겠죠? Bottom Sheet Fragment로 만드려고 합니당~!

## 📑 To-do

- [x] 리소스 각각 추가
- [x] xml 코드 짜는거 익숙해지기,, (안 한지 한 달은 되는거 같아유)
- [x] 알림창 타입 구분 (좋아요 ⇒ 해당 뮤멘트 상세보기로 이동, 공지 알림 ⇒ 공지사항 속 게시글으로, 마케팅 알림 ⇒ 목적에 맞는 위치로 이동 등)
- [ ] 알럿 뷰 짜기(일단 core-dependent Module)
- [x] 더미 넣어보기
- [x] BaseActivity Horizontal, Vertical Anim Add
