### ISSUE TITLE
[FEAT] 자잘한 API 다 붙이기

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#180]
## 🔈 Issue

- 간단한 api들 붙여놓으려구 합니다.
- 검색 부분 (+ 바텀시트까지) 제대로 로직 구현

## 📑 To-do

- [ ] 프로필 설정 유무 확인 (GET)
- [ ] 소식창 새로운 알림 유무 조회 (GET)
- [ ] 소식창 새로운 알림 읽음 처리(PATCH)
- [ ] 소식창 알림 제거(PATCH)
- [ ] 검색 분기처리 최적화
