### ISSUE TITLE
[FEAT] QA 전 확인 작업

### ISSUE THREAD

**Issue by jinsilWoo** [team-MUMENT/MUMENT-AOS#205]
## 🔈 Issue

QA 전 확인 작업 하려고 합니다.!

## 📑 To-do

- [ ] 수정하기 제안 알럿 하는건지 확인
- [ ] 바텀네비에 가려지는 데이터들 하단에 패딩 주기 (music detail)
- [ ] Overscroll mode never 로 통일
- [ ] 뮤멘트 카드? 00을 느낀 순간 이부분 카드 말줄임
- [ ] 뮤멘트 상세보기 내용 길면 스크롤바 할지 안할지
- [ ] 기록하기 ,프로필 세팅 키보드 모드 submit 변경
