### ISSUE TITLE
[CHORE] QA 이슈 3가지, 홈, 푸쉬, 소식창 관련

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#213]
## 🔈 Issue

일단 빠르게 해결할 수 있는 이슈들 하나씩 해결하려구 합니당~!!!

## 📑 To-do

- [x] [푸시 알림] 푸시알림 안울리고 앱 강제종료됨 이슈 해결
- [x] [소식창] 엠티뷰 적용 요청 및 텍스트 수정
- [x] [홈] 카드 그림자, 검색창 폰트 수정 요청
- [x] [홈/보관함/상세보기] 카드들 폰트 변경 및 최대 글자수 수정요청 (마이노 파트, 코맨트에 기재)
