### ISSUE TITLE
[HOTFIX] 네비 수정

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#215]
## 🔈 Issue

- 네비 bundle, intent extra 제대로 안 먹는 부분들 있어서 수정하려고 합니다.

## 📑 To-do

- [x] 수정하기에서 데이터 안 넘어감
- [x] 히스토리에서 데이터 안 넘어감
- [x] 자잘한 네비 처리
