### ISSUE TITLE
[FEAT] 잔여 QA 수정

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#217]
## 🔈 Issue

- 그림자 전체적으로 만들어서 모두 적용할 예정
- 평화형꺼 몇개 제가 수정할게요 (중간 중간 이슈에 끼워놓을 예정)

## 📑 To-do

- [x] "[곡 상세보기 엠티뷰] 텍스트 수정 요청" -> 재 체크
- [x] "Bold 관련 이슈, Home, Detail Module까지만" 텍스트 볼드처리 해결( sp to dp ) 
- [x] [홈] 카드 그림자 및 폰트, 검색창 폰트 수정 요청
- [x] [홈/보관함/상세보기] 카드들 폰트 변경 및 최대 글자수 수정요청
- [x] "[검색창 엠티뷰] 아이콘 위치 변경, 폰트 컬러 수정 요청" -> 검색어 부분 Span Color 처리
- [x] 페이지네이션 삭제 ( 히스토리, 뮤멘트 상세보기?였나 뮤직 상세보기)
