### ISSUE TITLE
[FIX] QA 2-1차 수정

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#224]
## 🔈 Issue

- 뭐가 엄청 많아서 되는대로 처리하겠습니다... todo 쌓기 가보자!
- 최근 검색어는 더 이상 안 쌓이게 data layer 로직 수정하겠습니당.
- 네비 부분은 아직 안 건드리고,,,, 나머지 할게요..

## 📑 To-do

- [x] [검색] 최근 검색한 곡 20개까지만 보이게 수정 요청 
- [ ] [알림] 뮤멘트 앱 로고 우상단 1 숫자 바뀌지 않음 -> {하... 알림 또 건드려야해}
- [x] [곡 상세보기] 내가 기록한 뮤멘트 카드에 좋아요 눌렀을 때 숫자가 변하지 않음  -> {이거 내가 하겠슴}
- [x] [곡 상세보기] 카드 3줄이후 말줄임 요청 및 UI 수정  -> {이것도}
- [x] [곡 상세보기] 모든 뮤멘트에 나의 비밀글 노출 요청  -> {이것도}
- [x] [뮤멘트 상세보기] 뮤멘트가 삭제된 경우, ‘삭제된 뮤멘트입니다.’ 팝업창 요청
- [x] MumentDialog 알럿 일부 수정
- [x] 바텀 네비 아이콘 틔어나오게 ( 정확한 수치로 하는건 모르겠음 )
