### ISSUE TITLE
[FIX] 2-2 QA 반영

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#228]
## 🔈 Issue

- 다시 한 번 부셔봅시다!!

## 📑 To-do

- [x] [뮤멘트 상세보기] 좋아요가 0일 때, 좋아요한 사용자 페이지로 넘어가지 않게 수정 요청 -> 내가 하겠슴
- [x] [검색창 엠티뷰] 아이콘 위치 변경, 폰트 컬러 수정 요청  -> 재요청(여백 조금만 더)
- [x] [검색창] 텍스트 한 줄을 두 줄로 수정 요청  -> 재요청( 이유를 모르겠음 난 두 줄로 했는데 한 줄이래 )
- [ ] [바텀 네비게이션] 그림자 수정요청 -> 재요청 ( 얘만 그림자 이상함 ㅋㅋ,,,)
- [x] [뮤멘트 상세보기] 텍스트간 간격 수정 요청 -> 후딱 하겠습니당
- [x] [뮤멘트 히스토리] 나의 뮤멘트 히스토리 비밀글- 뮤멘트 카드에 하트영역이 뜸
- [x] 좋아요 로티 적용
- [x] 인스타 공유 문제 조금이라도 수정
- [x] [수정하기] 수정 완료이후 뮤멘트 상세보기에서 백버튼 누르면 다시 뮤멘트 상세보기로 이동
