### ISSUE TITLE
[Chore] 리싸이클러뷰 아이템 만들기

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#23]
## 🔈 Issue

- 다시 들은 곡의 뮤멘트, 설렘을 느낀 순간 카드뷰를 완성 해보려고 합니다.

## 📑 To-do

- [x] 다시 들은 곡의 뮤멘트 data class 생성
- [x] 설렘을 느낀 순간 data class 생성
- [x] 각각의 item layout 생성
- [x] 각각의 listadapter class 생성
- [x] layout manager로 잘 뜨는지 확인
