### ISSUE TITLE
[FIX] APK 추출전 마무리 QA

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#232]
## 🔈 Issue

- 남은 QA 이슈 다 처리하겠습니다

## 📑 To-do

- [x] 전체 폰트 스타일 적용
- [ ] 바텀 네비 한 번만 더 찾아보기,,,
- [x] 나머지 이슈들 확인
- [x] [홈] MUMENT 로고 터치 시 새로고침 안됨  
- [x] [뮤멘트 상세보기] 뮤멘트가 삭제된 경우, ‘삭제된 뮤멘트입니다.’ 팝업창 요청
