### ISSUE TITLE
[REFACTOR] 하트 관련 Lottie Event 처리 오류 해결 및 일부 리펙

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#269]
## 🔈 Issue

- 하트 Lottie 부분이 급하게 틀어막은거라 타이밍 이슈가 있어서 해결 해두려고 함
- 추가적으로 일부 리펙토링 하려고 합니당.

## 📑 To-do

- [x] 노티 여부 이벤트 처리 단일화
   - [x] 노티 여부 DataStore로 이관
   - [x] 진입시 DataStore에 저장, Flow로 Get
   - [x] 노티 수신 시 DataStore에 저장, Flow로 Get
- [x] 하트 애니메이션 갱신 처리 확실하게
