### ISSUE TITLE
[DOCS] 리드미 작성

### ISSUE THREAD

**Issue by lhb8106** [team-MUMENT/MUMENT-AOS#27]
## 🔈 Issue
과제로 제출할 리드미를 작성합니다.

## 📑 To-do

- [x]  사용한 기술스텍(ex. 아키텍처 - MVVM, 비동기 - Coroutine 등등 자유롭게 작성)
- [x]  폴더링 구조
- [x]  서비스 이름과 간단한 프로젝트 설명
- [x]  각자 맡은 역할
