### ISSUE TITLE
[FEAT] 홈뷰 구현

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#30]
## 🔈 Issue

- 홈 뷰를 이제 완성하려고 합니다.

## 📑 To-do

- [x] 상단 배너용 layout 생성
- [x] 뷰페이저에 레이아웃 삽입
- [x] 일정 시간 후 전환되는 로직 구현
- [x] 더미 데이터 생성
- [x] 나머지 재사용 뷰들 recyclerview에 삽입
