### ISSUE TITLE
[FEAT] 곡 검색하기 뷰 작업

### ISSUE THREAD

**Issue by KkamSonLee** [team-MUMENT/MUMENT-AOS#39]
## 🔈 Issue

- 엠티 뷰 만들기
- 리스트뷰 공통 아이템 만들기

## 📑 To-do

- [ ] 검색 뷰 구현
- [x] 리스트뷰 데이터클래스 생성
- [x] 리스트뷰 레이아웃 구현
- [ ] 어댑터 설정 및 data binding 설정
