### ISSUE TITLE
[FEAT] 기록하기 뷰 Reset 팝업 기능 구현하기

### ISSUE THREAD

**Issue by jinsilWoo** [team-MUMENT/MUMENT-AOS#53]
## 🔈 Issue

기록하기 뷰에서 Reset  Button 을 누르면 나오는 팝업창을 구현할 예정입니다.!

## 📑 To-do

- [x] Reset Button 누르면 팝업창 띄우기
- [x] '예' 누르면 Reset 기능 구현
- [x] '아니오' 누르면 기존 유지
