### ISSUE TITLE
ex) [CHORE] CI 구축 및 Slack 연동

### ISSUE THREAD

**Issue by SONPYEONGHWA** [team-MUMENT/MUMENT-AOS#7]
## 🔈 Issue
- Feature 브랜치에서 작업 완료 후, PR을 날릴 때 해당 코드가 정상적으로 돌아가는 코드인지 검사.
- 만약 정상적으로 작동되는 코드일 때 apk파일을 자동으로 만들어주고 Slack채널로 던져준다.

## 📑 To-do
- [ ] Slack 앱, 채널 만들고 연동
- [ ] Github Action 설정
- [ ] 정상적으로 작동하는지 확인
